[db]
url = "sqlite:app.db?mode=rwc"
max_connections = 64

[web]
addr = "127.0.0.1:8081"
graceful_shutdown_timeout = "1s"
tracing = true

[web.static]
enable = true

[web.static.mapping.storage]
path = "/storage"
dir = "storage"
listing = true

[web.static.mapping.ui]
path = "/ui"
dir = "ui"
listing = true

[oauth]
authorization_url = "https://github.com/login/oauth/authorize"
client_id = "Ov23liT2qfXbByb1kPSL"
client_secret = "8f665beb9f075d16b4169b623448a5eb5a496b00"
scopes = ["read:user", "read:email"]

[jwt]
document_path = "keys/secret.pem"
expire_seconds = 1800