name: "Test"

on:
  pull_request:

jobs:
  check:
    name: "Cargo check"
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        toolchain: 
          - nightly
    steps:
      - uses: actions/checkout@v4
      - uses: FedericoCarboni/setup-ffmpeg@v3
      - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - run: rustup component add clippy rustfmt
      - run: cargo fmt --all -- --check
      #- run: cargo clippy -- -D warnings
      - run: cargo clippy
      - run: cargo build --verbose
      - run: cargo test --verbose
